version: "3.8"

services:
  database:
    image: mysql
    container_name: course_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: course
      MYSQL_USER: sastiam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

