version: "3.8"

services:
  database:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: course
      MYSQL_USER: sastiam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - course_db_data:/var/lib/mysql

volumes:
  course_db_data:


